apiVersion: v1
kind: Service
metadata:
  name: {{ include "mongodb.fullname" . }}
  labels:
    {{- include "mongodb.labels" . | nindent 4 }}
spec:
  ports:
    - name: mongodb
      port: {{ .Values.mongodb.port }}
  selector:
    {{- include "mongodb.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mongodb.fullname" . }}-exporter
  labels:
    {{- include "mongodb.labels" . | nindent 4 }}
  annotations:
    prometheus.io/scrape: "true"
spec:
  ports:
    - name: mongodb-exporter
      port: 9216
  selector:
    {{- include "mongodb.selectorLabels" . | nindent 4 }}
